services:

  db:
    image: postgres:16-alpine
    container_name: mosamatic3_postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=foobar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d db"]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 5432
    ports:
      - 5432:5432  # Required for running Django outside Docker but using PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    image: brecheisen/mosamatic3-nginx:latest
    container_name: mosamatic3_nginx
    ports:
      - "8001:80"
    volumes:
      - data:/data
    depends_on:
      - web

  web:
    build: .
    image: brecheisen/mosamatic3-web:latest
    container_name: mosamatic3_web
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_HOST # Will be defined by environment
      - POSTGRES_PORT=5432
    volumes:
      - data:/data
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

volumes:

  data:
  postgres_data: