FROM python:3.9

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim libpq-dev pkg-config cmake openssl wget git dos2unix \
    libgl1-mesa-glx libxrender1 libffi-dev libssl-dev build-essential pigz dcm2niix \
    ca-certificates curl gnupg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

COPY requirements-arm64.txt /requirements.txt
RUN pip install --upgrade pip setuptools wheel && \
    pip install -r /requirements.txt --verbose

RUN mkdir -p /data/static && \
    mkdir -p /data/datasets && \
    mkdir -p /data/uploads/{0..9} && chmod 777 -R /data/uploads

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN dos2unix /docker-entrypoint.sh

COPY src/mosamatic3 /src

WORKDIR /src

RUN apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/docker-entrypoint.sh"]
