# Generated by Django 5.1.1 on 2024-09-27 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOutputModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(editable=False, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=1024, unique=True)),
                ('status', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='FileSetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('path', models.CharField(editable=False, max_length=2048, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('path', models.CharField(editable=False, max_length=2048, unique=True)),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filesetmodel')),
            ],
        ),
    ]
