# Generated by Django 5.1.1 on 2024-11-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='installed',
        ),
    ]
