# Generated by Django 5.1.1 on 2024-11-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='installed',
            field=models.BooleanField(default=False),
        ),
    ]
