# Generated by Django 5.1.1 on 2024-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_taskprogressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='png_path',
            field=models.CharField(default=None, editable=False, max_length=2048, null=True),
        ),
    ]
